//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCSharp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DemoCSharp.ServiceReference1.HelloWorldResponse HelloWorld(DemoCSharp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(DemoCSharp.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name NameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Name", ReplyAction="*")]
        DemoCSharp.ServiceReference1.NameResponse Name(DemoCSharp.ServiceReference1.NameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Name", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.NameResponse> NameAsync(DemoCSharp.ServiceReference1.NameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DemoCSharp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DemoCSharp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemoCSharp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DemoCSharp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Name", Namespace="http://tempuri.org/", Order=0)]
        public DemoCSharp.ServiceReference1.NameRequestBody Body;
        
        public NameRequest() {
        }
        
        public NameRequest(DemoCSharp.ServiceReference1.NameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NameRequestBody {
        
        public NameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemoCSharp.ServiceReference1.NameResponseBody Body;
        
        public NameResponse() {
        }
        
        public NameResponse(DemoCSharp.ServiceReference1.NameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameResult;
        
        public NameResponseBody() {
        }
        
        public NameResponseBody(string NameResult) {
            this.NameResult = NameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DemoCSharp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DemoCSharp.ServiceReference1.WebService1Soap>, DemoCSharp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSharp.ServiceReference1.HelloWorldResponse DemoCSharp.ServiceReference1.WebService1Soap.HelloWorld(DemoCSharp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DemoCSharp.ServiceReference1.HelloWorldRequest inValue = new DemoCSharp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new DemoCSharp.ServiceReference1.HelloWorldRequestBody();
            DemoCSharp.ServiceReference1.HelloWorldResponse retVal = ((DemoCSharp.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.HelloWorldResponse> DemoCSharp.ServiceReference1.WebService1Soap.HelloWorldAsync(DemoCSharp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            DemoCSharp.ServiceReference1.HelloWorldRequest inValue = new DemoCSharp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new DemoCSharp.ServiceReference1.HelloWorldRequestBody();
            return ((DemoCSharp.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoCSharp.ServiceReference1.NameResponse DemoCSharp.ServiceReference1.WebService1Soap.Name(DemoCSharp.ServiceReference1.NameRequest request) {
            return base.Channel.Name(request);
        }
        
        public string Name() {
            DemoCSharp.ServiceReference1.NameRequest inValue = new DemoCSharp.ServiceReference1.NameRequest();
            inValue.Body = new DemoCSharp.ServiceReference1.NameRequestBody();
            DemoCSharp.ServiceReference1.NameResponse retVal = ((DemoCSharp.ServiceReference1.WebService1Soap)(this)).Name(inValue);
            return retVal.Body.NameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.NameResponse> DemoCSharp.ServiceReference1.WebService1Soap.NameAsync(DemoCSharp.ServiceReference1.NameRequest request) {
            return base.Channel.NameAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoCSharp.ServiceReference1.NameResponse> NameAsync() {
            DemoCSharp.ServiceReference1.NameRequest inValue = new DemoCSharp.ServiceReference1.NameRequest();
            inValue.Body = new DemoCSharp.ServiceReference1.NameRequestBody();
            return ((DemoCSharp.ServiceReference1.WebService1Soap)(this)).NameAsync(inValue);
        }
    }
}
